name: main

on:
  schedule:
    - cron: 01 */2 * * *
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Asia/Bangkok

jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Test SSH connection (This step is optional)
    - name: Test SSH connection
      run: |
        ssh -T git@github.com || true  # This will not fail the job even with exit code 1

    # Step 4: Initialize and update submodule
    - name: Initialize and update submodule
      run: |
        git submodule init
        git submodule update

    # Step 5: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 6: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 7: Run Tempest script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        ls -la  # List files in the current directory to ensure correct location
        php tempest.php --epg config=tempest.config.xml invgz
        if [ $? -ne 0 ]; then
          echo "Error: tempest.php failed to run."
          exit 1
        fi
        ls -la tempest_config/epg  # Verify if guide.xml is created
        if [ ! -f tempest_config/epg/guide.xml ]; then
          echo "Error: guide.xml was not created."
          exit 1
        fi

    # Step 8: Commit updated guide.xml
    - name: Commit and push updated guide.xml
      run: |
        if [ -f ./epg-grabber/tempest_config/epg/guide.xml ]; then
          # Switch to the submodule directory
          cd epg-grabber

          # Configure Git for the submodule
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Add guide.xml to the submodule
          git add tempest_config/epg/guide.xml

          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Skipping commit and push."
          else
            # Commit and push changes in the submodule
            export NOW=$(date +'%Y-%m-%dT%H:%M:%S')
            git commit -am "Automated guide.xml update ($NOW)"
            git push origin main
          fi

          # Switch back to the main repository
          cd ..

          # Commit the updated submodule reference in the main repository
          git add epg-grabber
          git commit -m "Update epg-grabber submodule reference"
          git push origin main
        else
          echo "Error: guide.xml was not found. Skipping commit and push."
        fi
