name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Test SSH connection
    - name: Test SSH connection
      run: ssh -T git@github.com || true  # This will not fail the job even with exit code 1

    # Step 4: Clone private repository
    - name: Clone private repository
      run: git clone git@github.com:akkradet/epg-grabber.git

    # Step 5: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 6: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 7: Run Tempest script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        php tempest.php --epg config=tempest.config.xml invgz

    # Step 8: Debug file paths and verify generation
    - name: Verify generated files
      run: |
        echo "Listing files in tempest_config/epg directory:"
        ls -la epg-grabber/tempest_config/epg || echo "Directory not found"
        echo "Checking individual file existence:"
        [ -f epg-grabber/tempest_config/epg/tempest_with_details.xml ] && echo "tempest_with_details.xml exists" || echo "tempest_with_details.xml not found"
        [ -f epg-grabber/tempest_config/epg/tempest.xml ] && echo "tempest.xml exists" || echo "tempest.xml not found"

    # Step 9: Stage and commit updated files
    - name: Stage and commit updated XML files
      run: |
        cd epg-grabber
        git add tempest_config/epg/*.xml
        git status
        git commit -m "Automated EPG update" || echo "No changes to commit"
        git push || echo "Push failed"

    # Optional: Add auto-commit action as a fallback
    - name: Commit using auto-commit action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated EPG update"
        file_pattern: "epg-grabber/tempest_config/epg/*.xml"
        repository: .
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        skip_dirty_check: false
        skip_fetch: false
        skip_checkout: false
        disable_globbing: false
