name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

   # Step 4: Clone the private repository using SSH
    - name: Clone private repository using SSH
      run: |
        # Make sure SSH key is available for the current session
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git clone git@github.com:akkradet/epg-grabber.git
        cd epg-grabber

    # Step 5: Checkout code (for PHP steps)
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 6: Set up Git identity
    - name: Set up Git identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    # Step 7: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3 # Specify correct PHP version
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1
		
    # Step 8: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 9: Run Tempest script
    - name: Run Tempest script
      run: |
        php tempest.php --epg config=tempest.config.xml invgz
        rm -f tempest_config/epg/guide.xml

    # Step 10: Pull latest from the repository
    - name: Pull latest
      run: git pull

    # Step 11: Commit and push updated epg.xml
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Automated EPG update'
        push_options: '--force'