name: Sync EPG Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-epg-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Clone the private repository
    - name: Clone private repository
      run: git clone git@github.com:akkradet/epg-grabber.git epg-grabber

    # Step 4: Copy XML files from private repo to public repo
    - name: Copy XML files
      run: |
        cp -r epg-grabber/tempest_config/epg/*.xml ./epg/

    # Step 5: Commit and push changes to public repo
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Sync EPG files from epg-grabber"
        file_pattern: "epg/*.xml"
