name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Test SSH connection (This step is optional)
    - name: Test SSH connection
      run: |
        ssh -T git@github.com || true  # This will not fail the job even with exit code 1

    # Step 4: Clone private repository
    - name: Clone private repository
      run: git clone git@github.com:akkradet/epg-grabber.git

    # Step 5: List contents of the repository and check for necessary files
    - name: List repository contents and check for required files
      run: |
        cd epg-grabber
        echo "Listing contents of the repository to check for tempest.php and XML files:"
        ls -l
        ls -l tempest_config/epg/*.xml || echo "No XML files found in tempest_config/epg/"

    # Step 6: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 7: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 8: Check if tempest.php exists and run the script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        if [ -f tempest.php ]; then
          php tempest.php --epg config=tempest.config.xml invgz
          rm -f tempest_config/epg/tempest_with_details.xml
          rm -f tempest_config/epg/tempest.xml
        else
          echo "tempest.php not found in the repository"
          exit 1
        fi

    # Step 9: Commit and push updated epg.xml files if they exist
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated EPG update"
        file_pattern: "tempest_config/epg/*.xml"
