name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Test SSH connection (This step is optional)
    - name: Test SSH connection
      run: |
        ssh -T git@github.com || true  # This will not fail the job even with exit code 1

    # Step 4: Clone private repository
    - name: Clone private repository
      run: git clone git@github.com:akkradet/epg-grabber.git

    # Step 5: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 6: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 7: Run Tempest script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        php tempest.php --epg config=tempest.config.xml invgz

    # Step 8: Pull latest from the repository
    - name: Pull latest
      run: git pull

    # Step 9: Commit and push updated epg.xml
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "Automated EPG update"
          branch: main
          file_pattern: "tempest_config/**"
