name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-ssh-key-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Clone private repository
    - name: Clone private repository
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: git clone git@github.com:akkradet/epg-grabber.git

    # Step 4: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 5: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 6: Run Tempest script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        php tempest.php --epg config=tempest.config.xml invgz
        rm -f tempest_config/epg/tempest_with_details.xml
        rm -f tempest_config/epg/tempest.xml

    # Step 7: Commit updated epg.xml
    - name: Commit and push updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated EPG update"
        file_pattern: "tempest_config/epg/*.xml"