name: Sync EPG Files and Run Tempest Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-and-run-tempest:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the public repository
    - name: Checkout public repository
      uses: actions/checkout@v2

    # Step 2: Configure SSH key
    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 3: Clone the private repository
    - name: Clone private repository
      run: git clone git@github.com:akkradet/epg-grabber.git epg-grabber

    # Step 4: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: 8.3
        extensions: xml, imagick, zip, curl
        ini-values: memory_limit=-1

    # Step 5: Verify PHP installation
    - name: Verify PHP installation
      run: php -v

    # Step 6: Run Tempest script
    - name: Run Tempest script
      run: |
        cd epg-grabber
        if [ -f tempest.php ]; then
          php tempest.php --epg config=tempest.config.xml invgz
        else
          echo "tempest.php not found in the repository"
          exit 1
        fi

    # Step 7: Copy XML files from private repo to public repo
    - name: Check and Copy XML files
      run: |
        if [ -d "epg-grabber/tempest_config/epg" ]; then
            mkdir -p ./epg/
            cp -r epg-grabber/tempest_config/epg/*.xml ./epg/
        else
            echo "No XML files to copy."
        fi

    # Step 8: Commit and push changes to public repo
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Sync EPG files from epg-grabber and run Tempest script"
        file_pattern: "epg/*.xml"
